# Introduction to the Step 1 script----
# Step 1 Learning Objectives:
# 1 - Step 1 serves as your gateway to R scripts and, as such, you will learn the proper 'anatomy' for any R script.
# 2 - Learn how to install packages and load libraries into your R environment
# 3 - Understand the various file types that describe RNAseq data and how to import these files (e.g. kallisto read mapping data) into R
# 4 - Learn basic tools for annotation

# Notes:
# This script is organized into 'chunks' of code, and the final chunk (called 'the essentials') is a minimal representation of this script.


# load packages----
# use install.packages("package_name") if not found
#use setRepositories() if no install candidate present
install.packages("rhdf5")
install.packages("tidyverse")
install.packages("tximport")
install.packages("biomaRt")
library(rhdf5) #provides functions for handling hdf5 file formats (kallisto outputs bootstraps in this format)
library(tidyverse) # provides access to Hadley Wickham's collection of R packages for data science, which we will use throughout the course
library(tximport) # package for getting Kallisto results into R
library(biomaRt) # for annotations

# read in your study design ----
#there are LOTS of ways to read data into R, but the readr package (from tidyverse) is one of the simplest
targets <- read_tsv("design.csv")
sampleLabels <- targets$directory 
# you can easily create file paths to the abundance files generated by Kallisto using the 'file.path' function
path <- file.path("mapped", targets$directory, "abundance.tsv") # set file paths to your mapped data
# now check to make sure this path is correct by seeing if the files exist
all(file.exists(path)) 
# the functions which(), any() and all() take logical vectors as their argument. The any()
# function will return TRUE if one or more of the elements in the logical vector is TRUE. The all() function
# will return TRUE if every element in the logical vector is TRUE.


# Get annotations ----
# The annotation method described in the code chunk above works great if an organism-specific data base package exists for your organisms of interest
# however, this is only the case for human, mouse and rat....
# so, this optional code chunk shows one way you can get annotation data for other target organisms
# in this example, we're retrieving 1:1 mappings between transcript identifiers and gene symbols for tomato


listMarts() #default host is ensembl.org, and most current release of mammalian genomes
#listMarts(host="parasite.wormbase.org") #access to parasite worm genomes
#listMarts(host="protists.ensembl.org") #access to protozoan genomes
listMarts(host="plants.ensembl.org") #access to plant genomes

#choose the 'mart' you want to work with
#myMart <- useMart(biomart="ENSEMBL_MART_ENSEMBL") # marts for mammalian genomes
myMart <- useMart(biomart="plants_mart", host="plants.ensembl.org") # marts for plant genomes

#take a look at all available datasets within the selected mart
available.datasets <- listDatasets(myMart)
#now grab the ensembl annotations for tomato
lyc.anno <- useMart(biomart="plants_mart", dataset = "slycopersicum_eg_gene", host="plants.ensembl.org")
lyc.attributes <- listAttributes(lyc.anno)
#take a look at all available attributes within the selected tomato annotation
Tx.lyc <- getBM(attributes=c('ensembl_transcript_id',
                             'ensembl_gene_id', 'description'),
                mart = lyc.anno)
#turn it into a table
Tx.lyc <- as_tibble(Tx.lyc) 
#we need to rename the two columns we just retreived from biomart
Tx.lyc <- dplyr::rename(Tx.lyc, target_id = ensembl_transcript_id, gene_name = ensembl_gene_id)
#transcrip ID needs to be the first column in the dataframe
Tx.lyc <- dplyr::select(Tx.lyc, "target_id", "gene_name")


# import Kallisto transcript counts into R using Tximport ----
# copy the abundance files to the working directory and rename so that each sample has a unique name
Txi_gene <- tximport(path, 
                     type = "kallisto", 
                     tx2gene = Tx.lyc, #Mapping from transcript IDs to gene IDs 
                     txOut = FALSE, #How does the result change if this =FALSE vs =TRUE?
                     countsFromAbundance = "lengthScaledTPM",
                     ignoreTxVersion = F)

Txi_trans <- tximport(path, 
                     type = "kallisto", 
                     tx2gene = Tx.lyc, #Mapping from transcript IDs to gene IDs 
                     txOut = TRUE, #How does the result change if this =FALSE vs =TRUE?
                     countsFromAbundance = "lengthScaledTPM",
                     ignoreTxVersion = F)


